meta_name: "Tem Role?"
meta_title: "Tem Role? - Conectando a cena de música eletrônica brasileira"
meta_description: "Descubra as festas que estão rolando ao redor do Brasil."
meta_image: "logo_neon.png"
